# Generated by Django 3.1.12 on 2021-06-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210617_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pagarme_customer_id',
            field=models.IntegerField(default=5739372),
            preserve_default=False,
        ),
    ]
