# Generated by Django 3.1.12 on 2021-06-18 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_pagarme_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pagarme_customer_id',
            field=models.PositiveBigIntegerField(),
        ),
    ]
