# Generated by Django 3.1.12 on 2021-06-18 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210618_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pagarme_customer_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
