# Generated by Django 3.1.11 on 2021-06-01 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='access_hash',
            field=models.CharField(help_text='Hash curto para link de acesso', max_length=64, unique=True),
        ),
    ]
