# Generated by Django 3.1.12 on 2021-06-12 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_auto_20210608_2249'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('NONE', 'Ainda não avaliada'), ('APPROVED', 'Aprovada'), ('ATTENTION', 'Carece de atenção para alterações'), ('CANCELED', 'Cancelada')], default='NONE', max_length=9),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('SINGLE', 'Única Imagem'), ('VIDEO', 'Único vídeo'), ('GALLERY', 'Diversos, vídeos ou imagens')], default='SINGLE', max_length=7),
        ),
    ]
