# Generated by Django 3.1.12 on 2021-06-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_auto_20210615_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='archive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='postfile',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
