# Generated by Django 3.1.12 on 2021-06-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_auto_20210618_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='status',
            field=models.CharField(choices=[('TRIAL', 'Em fase de teste'), ('PAID', 'Pago'), ('UNPAID', 'Não pago'), ('ENDED', 'Concluída'), ('CANCELED', 'Cancelada')], default='UNPAID', max_length=8),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processando'), ('AUTHORIZED', 'Autorizado'), ('PAID', 'Pago'), ('REFUNDED', 'Reembolsado'), ('WAITING_PAYMENT', 'Aguardando pagamento'), ('PENDING_REFUND', 'Reembolso pendente'), ('REFUSED', 'Recusada')], default='PAID', max_length=15),
        ),
    ]
